import { mkdir, writeFile, cp } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { SiteSpec } from './types.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const TEMPLATES_DIR = join(__dirname, '..', 'templates');
const PROJECTS_DIR = process.env.PROJECTS_DIR ?? '/tmp/wv-projects';

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function renderAstroPage(spec: SiteSpec): string {
  const services = spec.services
    .map(
      (s) => `
    <div class="service-card">
      ${s.icon ? `<div class="service-icon">${escapeHtml(s.icon)}</div>` : ''}
      <h3>${escapeHtml(s.name)}</h3>
      <p>${escapeHtml(s.description)}</p>
    </div>`,
    )
    .join('\n');

  const testimonials =
    spec.testimonials
      ?.map(
        (t) => `
    <blockquote class="testimonial">
      <p>"${escapeHtml(t.quote)}"</p>
      <cite>— ${escapeHtml(t.author)}</cite>
    </blockquote>`,
      )
      .join('\n') ?? '';

  return `---
// Auto-generated by WebVulture — do not edit manually
const spec = ${JSON.stringify(spec, null, 2)};
---
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(spec.business_name)} — ${escapeHtml(spec.tagline)}</title>
  <style>
    :root {
      --primary: ${escapeHtml(spec.brand.primary_color)};
      --font: ${spec.brand.font_style === 'classic' ? 'Georgia, serif' : 'system-ui, sans-serif'};
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: var(--font); color: #1a1a1a; line-height: 1.6; }
    a { color: var(--primary); }

    /* Nav */
    nav { background: var(--primary); color: #fff; padding: 1rem 2rem; display: flex; justify-content: space-between; align-items: center; }
    nav .brand { font-size: 1.25rem; font-weight: 700; color: #fff; text-decoration: none; }
    nav ul { list-style: none; display: flex; gap: 1.5rem; }
    nav a { color: rgba(255,255,255,0.85); text-decoration: none; font-size: 0.9rem; }

    /* Hero */
    .hero { background: linear-gradient(135deg, var(--primary) 0%, #1a1a2e 100%); color: #fff; padding: 6rem 2rem; text-align: center; }
    .hero h1 { font-size: clamp(2rem, 5vw, 3.5rem); font-weight: 800; margin-bottom: 1rem; }
    .hero p { font-size: 1.2rem; opacity: 0.85; max-width: 640px; margin: 0 auto 2rem; }
    .btn { display: inline-block; background: #fff; color: var(--primary); padding: 0.85rem 2rem; border-radius: 50px; font-weight: 700; text-decoration: none; transition: transform 0.15s; }
    .btn:hover { transform: translateY(-2px); }

    /* Sections */
    section { padding: 5rem 2rem; max-width: 1100px; margin: 0 auto; }
    h2 { font-size: 2rem; font-weight: 700; margin-bottom: 2rem; }

    /* Services grid */
    .services-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 1.5rem; }
    .service-card { background: #f8f9fa; border-radius: 12px; padding: 2rem; }
    .service-card h3 { font-size: 1.1rem; font-weight: 700; margin-bottom: 0.5rem; }
    .service-card p { font-size: 0.9rem; color: #555; }

    /* About */
    .about-section { background: #f8f9fa; }
    .about-section section { }

    /* Testimonials */
    .testimonials-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 1.5rem; }
    .testimonial { background: #fff; border-left: 4px solid var(--primary); padding: 1.5rem; border-radius: 0 12px 12px 0; box-shadow: 0 2px 8px rgba(0,0,0,0.06); }
    .testimonial cite { display: block; margin-top: 0.75rem; font-size: 0.85rem; color: #777; }

    /* Contact */
    .contact-section { background: var(--primary); color: #fff; text-align: center; }
    .contact-section section { }
    .contact-section h2 { color: #fff; }
    .contact-section p { opacity: 0.85; margin-bottom: 0.5rem; }
    .btn-outline { background: transparent; color: #fff; border: 2px solid #fff; }

    /* Footer */
    footer { background: #1a1a1a; color: rgba(255,255,255,0.6); text-align: center; padding: 2rem; font-size: 0.85rem; }
  </style>
</head>
<body>

<nav>
  <a class="brand" href="/">${escapeHtml(spec.business_name)}</a>
  <ul>
    <li><a href="#services">Services</a></li>
    <li><a href="#about">About</a></li>
    <li><a href="#contact">Contact</a></li>
  </ul>
</nav>

<!-- Hero -->
<div class="hero">
  <h1>${escapeHtml(spec.hero.headline)}</h1>
  <p>${escapeHtml(spec.hero.subheadline)}</p>
  <a href="#contact" class="btn">${escapeHtml(spec.hero.cta_text)}</a>
</div>

<!-- Services -->
<section id="services">
  <h2>Our Services</h2>
  <div class="services-grid">
    ${services}
  </div>
</section>

<!-- About -->
<div class="about-section">
  <section id="about">
    <h2>About Us</h2>
    <p>${escapeHtml(spec.about.body)}</p>
  </section>
</div>

${
  testimonials
    ? `<!-- Testimonials -->
<section id="testimonials">
  <h2>What Our Clients Say</h2>
  <div class="testimonials-grid">
    ${testimonials}
  </div>
</section>`
    : ''
}

<!-- Contact -->
<div class="contact-section">
  <section id="contact">
    <h2>Get In Touch</h2>
    ${spec.contact.phone ? `<p>📞 ${escapeHtml(spec.contact.phone)}</p>` : ''}
    ${spec.contact.email ? `<p>✉️ ${escapeHtml(spec.contact.email)}</p>` : ''}
    ${spec.contact.address ? `<p>📍 ${escapeHtml(spec.contact.address)}</p>` : ''}
    <br />
    <a href="mailto:${escapeHtml(spec.contact.email ?? '')}" class="btn btn-outline">${escapeHtml(spec.contact.cta_text)}</a>
  </section>
</div>

<!-- Footer -->
<footer>
  <p>&copy; ${new Date().getFullYear()} ${escapeHtml(spec.business_name)}. ${escapeHtml(spec.footer.tagline)}</p>
  <p style="margin-top:0.5rem;font-size:0.75rem;opacity:0.4;">Built with WebVulture</p>
</footer>

</body>
</html>
`;
}

export async function scaffoldAstroProject(
  prototypeVersionId: number,
  spec: SiteSpec,
): Promise<string> {
  const projectDir = join(PROJECTS_DIR, `prototype-${prototypeVersionId}`);

  await mkdir(join(projectDir, 'src', 'pages'), { recursive: true });
  await mkdir(join(projectDir, 'public'), { recursive: true });

  // package.json for the Astro site
  await writeFile(
    join(projectDir, 'package.json'),
    JSON.stringify(
      {
        name: `prototype-${prototypeVersionId}`,
        type: 'module',
        scripts: { build: 'astro build', dev: 'astro dev', preview: 'astro preview' },
        dependencies: { astro: '^5.0.0' },
      },
      null,
      2,
    ),
  );

  // astro.config.mjs
  await writeFile(
    join(projectDir, 'astro.config.mjs'),
    `import { defineConfig } from 'astro/config';
export default defineConfig({ output: 'static' });
`,
  );

  // Main index page
  await writeFile(join(projectDir, 'src', 'pages', 'index.astro'), renderAstroPage(spec));

  // Store spec JSON alongside the project
  await writeFile(join(projectDir, 'site-spec.json'), JSON.stringify(spec, null, 2));

  return projectDir;
}
